import type { PermissionKey, Role } from "@/types/auth";

export const permissionsByRole: Record<Role, PermissionKey[]> = {
  medicina: [
    "view_dashboard",
    "manage_profile",
    "manage_patients",
    "manage_clinical_records",
    "issue_certificates",
    "request_laboratory",
    "manage_prescriptions",
    "view_monthly_report",
  ],
  enfermeria: [
    "view_dashboard",
    "manage_profile",
    "manage_triage",
    "manage_vital_signs",
    "manage_referrals",
    "manage_procedures",
    "view_monthly_report",
  ],
  laboratorio: [
    "view_dashboard",
    "manage_profile",
    "manage_laboratory_requests",
    "manage_laboratory_results",
    "manage_test_catalog",
    "view_monthly_report",
  ],
  odontologia: [
    "view_dashboard",
    "manage_profile",
    "manage_patients",
    "manage_dental_chart",
    "manage_procedures",
    "issue_certificates",
    "view_monthly_report",
  ],
  psicologia: [
    "view_dashboard",
    "manage_profile",
    "manage_patients",
    "manage_sessions",
    "manage_followups",
    "manage_referrals",
    "view_monthly_report",
  ],
  farmacia: [
    "view_dashboard",
    "manage_profile",
    "manage_prescriptions",
    "manage_medication_delivery",
    "manage_stock",
    "manage_kardex",
    "manage_alerts",
    "view_monthly_report",
  ],
  admin: [
    "view_dashboard",
    "manage_profile",
    "manage_users",
    "manage_roles",
    "manage_catalogs",
    "manage_templates",
    "view_audit",
    "manage_settings",
  ],
};
